In [52]:
# Experiment 14: Data Binning and Data Formatting in Python
# Name: Rachit Jajoo
# PRN: 25070123088
# Batch: ENTC - B1

DATASET 1 UPLOADING...

In [53]:
# Dataset 1 Import
import pandas as pd
import numpy as np

data = {
    'Product': ['Laptop', 'Mobile', 'Tablet', 'Headphones', 'Smartwatch', 'Camera'],
    'Price': [55000, 20000, 30000, 2000, 8000, 45000],
    'Units_Sold': [25, 60, 35, 80, 50, 15]
}

df = pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [54]:
# Data Binning for Dataset 1

bins1 = [0, 10000, 30000, 60000]
labels1 = ['Low', 'Medium', 'High']

df['Price_Category'] = pd.cut(df['Price'], bins=bins1, labels=labels1)

print(df)

      Product  Price  Units_Sold Price_Category
0      Laptop  55000          25           High
1      Mobile  20000          60         Medium
2      Tablet  30000          35         Medium
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low
5      Camera  45000          15           High

In [55]:
# Binning Units Sold for Dataset 1
bins2 = [0, 30, 60, 100]
labels2 = ['Low Sales', 'Medium Sales', 'High Sales']

df['Sales_Category'] = pd.cut(df['Units_Sold'], bins=bins2, labels=labels2)

print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      Laptop  55000          25           High      Low Sales
1      Mobile  20000          60         Medium   Medium Sales
2      Tablet  30000          35         Medium   Medium Sales
3  Headphones   2000          80            Low     High Sales
4  Smartwatch   8000          50            Low   Medium Sales
5      Camera  45000          15           High      Low Sales

In [56]:
# Checking Data Types for Dataset 1
print(df.dtypes)

Product             object
Price                int64
Units_Sold           int64
Price_Category    category
Sales_Category    category
dtype: object

In [57]:
# Data Formatting for Dataset 1
# Convert Data Type

print(df.dtypes)

df['Units_Sold'] = df['Units_Sold'].astype(float)

print(df.dtypes)

df

Product             object
Price                int64
Units_Sold           int64
Price_Category    category
Sales_Category    category
dtype: object
Product             object
Price                int64
Units_Sold         float64
Price_Category    category
Sales_Category    category
dtype: object

      Product  Price  Units_Sold Price_Category Sales_Category
0      Laptop  55000        25.0           High      Low Sales
1      Mobile  20000        60.0         Medium   Medium Sales
2      Tablet  30000        35.0         Medium   Medium Sales
3  Headphones   2000        80.0            Low     High Sales
4  Smartwatch   8000        50.0            Low   Medium Sales
5      Camera  45000        15.0           High      Low Sales

In [58]:
# Convert Text to Uppercase for Dataset 1
df['Product'] = df['Product'].str.upper()

print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
3  HEADPHONES   2000        80.0            Low     High Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
5      CAMERA  45000        15.0           High      Low Sales

In [59]:
# Rounding Values for Dataset 1
df['Price'] = df['Price'].round(2)

print(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
3  HEADPHONES   2000        80.0            Low     High Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
5      CAMERA  45000        15.0           High      Low Sales

In [60]:
# Additional Operations for Dataset 1
# Sort data
df.sort_values(by='Price', ascending=False, inplace=True)
print(df)

# Note for self: Python arranges data in ascending order automatically when tasked to.
# Here we are overwriting the table so we used inplace command.
# To make it descending, you cannot use a new command. You have to modify ascending.

      Product  Price  Units_Sold Price_Category Sales_Category
0      LAPTOP  55000        25.0           High      Low Sales
5      CAMERA  45000        15.0           High      Low Sales
2      TABLET  30000        35.0         Medium   Medium Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
3  HEADPHONES   2000        80.0            Low     High Sales

In [61]:
# Display Unique Values for Dataset 1
print(df['Price_Category'].unique())

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

DATASET 2 UPLOADING...

In [62]:
# Dataset 2 Import: Food Delivery orders
import pandas as pd
import numpy as np

data = {
    'Order_ID': ['01', '02', '03', '04', '05', '06', '07', '08'],
    'Order_Value': [250, 450, 120, 600, 300, 150, 500, 220],
    'Delivery_Time': [30, 45, 25, 60, 35, 20, 50, 28],
    'Distance_km': [5, 8, 3, 10, 6, 2, 9, 4]
}

df = pd.DataFrame(data)

print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km
0       01          250             30            5
1       02          450             45            8
2       03          120             25            3
3       04          600             60           10
4       05          300             35            6
5       06          150             20            2
6       07          500             50            9
7       08          220             28            4

In [63]:
# Data Binning (Order Value) for Dataset 2
bins_val = [0, 200, 400, 700]
labels_val = ['Low', 'Medium', 'High']

df['Order_Category'] = pd.cut(df['Order_Value'], bins=bins_val, labels=labels_val)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category
0       01          250             30            5         Medium
1       02          450             45            8           High
2       03          120             25            3            Low
3       04          600             60           10           High
4       05          300             35            6         Medium
5       06          150             20            2            Low
6       07          500             50            9           High
7       08          220             28            4         Medium

In [64]:
# Binning Delivery Speed for Dataset 2
bins = [0, 30, 50, 70]
labels = ['Fast', 'Medium', 'Slow']

df['Delivery_Speed'] = pd.cut(df['Delivery_Time'], bins=bins, labels=labels)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category  \
0       01          250             30            5         Medium
1       02          450             45            8           High
2       03          120             25            3            Low
3       04          600             60           10           High
4       05          300             35            6         Medium
5       06          150             20            2            Low
6       07          500             50            9           High
7       08          220             28            4         Medium

  Delivery_Speed
0           Fast
1         Medium
2           Fast
3           Slow
4         Medium
5           Fast
6         Medium
7           Fast

In [65]:
# Binning Delivery Distance for Dataset 2

bins = [0, 3, 7, 12]
labels = ['Short Distance', 'Medium Distance', 'Long Distance']

df['Distance_Category'] = pd.cut(df['Distance_km'], bins=bins, labels=labels)

print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category  \
0       01          250             30            5         Medium
1       02          450             45            8           High
2       03          120             25            3            Low
3       04          600             60           10           High
4       05          300             35            6         Medium
5       06          150             20            2            Low
6       07          500             50            9           High
7       08          220             28            4         Medium

  Delivery_Speed Distance_Category
0           Fast   Medium Distance
1         Medium     Long Distance
2           Fast    Short Distance
3           Slow     Long Distance
4         Medium   Medium Distance
5           Fast    Short Distance
6         Medium     Long Distance
7           Fast   Medium Distance

In [66]:
# Checking Data Types for Dataset 2
print(df.dtypes)

Order_ID               object
Order_Value             int64
Delivery_Time           int64
Distance_km             int64
Order_Category       category
Delivery_Speed       category
Distance_Category    category
dtype: object

In [68]:
# Data Formatting for Dataset 2
# Convert Data Type

print(df.dtypes)

df['Delivery_Time'] = df['Delivery_Time'].astype(float)

df

Order_ID               object
Order_Value             int64
Delivery_Time         float64
Distance_km             int64
Order_Category       category
Delivery_Speed       category
Distance_Category    category
dtype: object

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Category,Delivery_Speed,Distance_Category
0,01,250,30.0,5,Medium,Fast,Medium Distance
1,02,450,45.0,8,High,Medium,Long Distance
2,03,120,25.0,3,Low,Fast,Short Distance
3,04,600,60.0,10,High,Slow,Long Distance
4,05,300,35.0,6,Medium,Medium,Medium Distance
5,06,150,20.0,2,Low,Fast,Short Distance
6,07,500,50.0,9,High,Medium,Long Distance
7,08,220,28.0,4,Medium,Fast,Medium Distance

In [71]:
# Count of Categories for Dataset 2
print("Distance Category Count:\n", df['Distance_Category'].value_counts())
print("\n Delivery Speed Count:\n", df['Delivery_Speed'].value_counts())
print("\n Order Category Count:\n", df['Order_Category'].value_counts())

Distance Category Count:
 Distance_Category
Medium Distance    3
Long Distance      3
Short Distance     2
Name: count, dtype: int64

 Delivery Speed Count:
 Delivery_Speed
Fast      4
Medium    3
Slow      1
Name: count, dtype: int64

 Order Category Count:
 Order_Category
Medium    3
High      3
Low       2
Name: count, dtype: int64

In [72]:
# Sorting By Order Value for Dataset 2
df_sorted = df.sort_values(by='Order_Value')
print(df_sorted)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category  \
2       03          120           25.0            3            Low
5       06          150           20.0            2            Low
7       08          220           28.0            4         Medium
0       01          250           30.0            5         Medium
4       05          300           35.0            6         Medium
1       02          450           45.0            8           High
6       07          500           50.0            9           High
3       04          600           60.0           10           High

  Delivery_Speed Distance_Category
2           Fast    Short Distance
5           Fast    Short Distance
7           Fast   Medium Distance
0           Fast   Medium Distance
4         Medium   Medium Distance
1         Medium     Long Distance
6         Medium     Long Distance
3           Slow     Long Distance

In [73]:
# Convert Text to Uppercase for Order Category in Dataset 2
df['Order_Category'] = df['Order_Category'].str.upper()

print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category  \
0       01          250           30.0            5         MEDIUM
1       02          450           45.0            8           HIGH
2       03          120           25.0            3            LOW
3       04          600           60.0           10           HIGH
4       05          300           35.0            6         MEDIUM
5       06          150           20.0            2            LOW
6       07          500           50.0            9           HIGH
7       08          220           28.0            4         MEDIUM

  Delivery_Speed Distance_Category
0           Fast   Medium Distance
1         Medium     Long Distance
2           Fast    Short Distance
3           Slow     Long Distance
4         Medium   Medium Distance
5           Fast    Short Distance
6         Medium     Long Distance
7           Fast   Medium Distance