In [11]:
# Experiment 15: Data Normalization and Data Type Conversion
# Name: Rachit Jajoo
# PRN: 25070123088
# Batch: ENTC - B1

Part A: Data Normalization

In [12]:
# Importing Dataset 1
import pandas as pd
import numpy as np

data = {
    'Product': ['Laptop', 'Mobile', 'Tablet', 'Headphones', 'Smartwatch', 'Camera'],
    'Price': [55000, 20000, 30000, 2000, 8000, 45000],
    'Units_Sold': [25, 60, 35, 80, 50, 15],
    'Discount': [10,15,12,20,18,8]
}

df = pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60        15
2      Tablet  30000          35        12
3  Headphones   2000          80        20
4  Smartwatch   8000          50        18
5      Camera  45000          15         8

In [13]:
# Dataset 1 Code 1:  Min-Max Normalization for Price

df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())

print("\n Min-Max Normalized Price \n")
print(df[['Product', 'Price', 'Price_MinMax']])

 Min-Max Normalized Price

      Product  Price  Price_MinMax
0      Laptop  55000      1.000000
1      Mobile  20000      0.339623
2      Tablet  30000      0.528302
3  Headphones   2000      0.000000
4  Smartwatch   8000      0.113208
5      Camera  45000      0.811321

In [14]:
# Dataset 1 Code 2: Normalizing Multiple Columns

cols = ['Price', 'Units_Sold', 'Discount']
df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())

print("\n Normalized Dataset \n")
print(df_norm)

 Normalized Dataset

      Price  Units_Sold  Discount
0  1.000000    0.153846  0.166667
1  0.339623    0.692308  0.583333
2  0.528302    0.307692  0.333333
3  0.000000    1.000000  1.000000
4  0.113208    0.538462  0.833333
5  0.811321    0.000000  0.000000

In [15]:
# Dataset 1 Code 3: Z score Normalization

df['Unit_Zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()

print("\n Z-Score Normalized Dataset \n")
print(df[['Product', 'Units_Sold', 'Unit_Zscore']])

 Z-Score Normalized Dataset

      Product  Units_Sold  Unit_Zscore
0      Laptop          25    -0.799885
1      Mobile          60     0.660775
2      Tablet          35    -0.382554
3  Headphones          80     1.495437
4  Smartwatch          50     0.243443
5      Camera          15    -1.217216

In [18]:
# Dataset 1 Code 4: Decimal Scaling

df['Price_Decimal'] = df['Price'] / 100000

print("\n Decimal Scaled Dataset \n")
print(df[['Product', 'Price', 'Price_Decimal']])

 Decimal Scaled Dataset

      Product  Price  Price_Decimal
0      Laptop  55000           0.55
1      Mobile  20000           0.20
2      Tablet  30000           0.30
3  Headphones   2000           0.02
4  Smartwatch   8000           0.08
5      Camera  45000           0.45

Part B: Turning Categorical Varables Into Quantitative Variables In Python

In [19]:
# Importing Dataset 2
import pandas as pd
import numpy as np
data = {
'Order_ID':[101,102,103,104,105,106],
'Customer_Gender':['Male','Female','Female','Male','Female','Male'],
'Payment_Method':['UPI','Credit Card','Debit Card','COD','UPI','Debit Card'],
'Product_Category':['Electronics','Clothing','Home','Electronics','Beauty','Electronics'],
'City':['Pune','Mumbai','Delhi','Bangalore','Pune','Hyderabad'],
'Order_Value':[4500,2300,3200,5200,1800,4100]
}

df = pd.DataFrame(data)

print(df)

   Order_ID Customer_Gender Payment_Method Product_Category       City  \
0       101            Male            UPI      Electronics       Pune
1       102          Female    Credit Card         Clothing     Mumbai
2       103          Female     Debit Card             Home      Delhi
3       104            Male            COD      Electronics  Bangalore
4       105          Female            UPI           Beauty       Pune
5       106            Male     Debit Card      Electronics  Hyderabad

   Order_Value
0         4500
1         2300
2         3200
3         5200
4         1800
5         4100

In [22]:
# Dataset 2 Code 1: Label Encoding - method one
# https://scikit-learn.org/stable/ is the site to find the data for this.

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Gender_Label'] = le.fit_transform(df['Customer_Gender'])
df['City_Label'] = le.fit_transform(df['City'])
print(df)

   Order_ID Customer_Gender Payment_Method Product_Category       City  \
0       101            Male            UPI      Electronics       Pune
1       102          Female    Credit Card         Clothing     Mumbai
2       103          Female     Debit Card             Home      Delhi
3       104            Male            COD      Electronics  Bangalore
4       105          Female            UPI           Beauty       Pune
5       106            Male     Debit Card      Electronics  Hyderabad

   Order_Value  Gender_Label  City_Label
0         4500             1           4
1         2300             0           3
2         3200             0           1
3         5200             1           0
4         1800             0           4
5         4100             1           2

In [23]:
# Dataset 2 Code 2: One Hot Encoding - method two
df_encoded = pd.get_dummies(df, columns=['Payment_Method'])
print(df_encoded)

   Order_ID Customer_Gender Product_Category       City  Order_Value  \
0       101            Male      Electronics       Pune         4500
1       102          Female         Clothing     Mumbai         2300
2       103          Female             Home      Delhi         3200
3       104            Male      Electronics  Bangalore         5200
4       105          Female           Beauty       Pune         1800
5       106            Male      Electronics  Hyderabad         4100

   Gender_Label  City_Label  Payment_Method_COD  Payment_Method_Credit Card  \
0             1           4               False                       False
1             0           3               False                        True
2             0           1               False                       False
3             1           0                True                       False
4             0           4               False                       False
5             1           2               False                       False

   Payment_Method_Debit Card  Payment_Method_UPI
0                      False                True
1                      False               False
2                       True               False
3                      False               False
4                      False                True
5                       True               False

In [24]:
# Dataset 2 Code 3: Dummy Encoding (drop first) - method three
df_dummy = pd.get_dummies(df, columns=['Payment_Method'], drop_first=True)
print(df_dummy)

   Order_ID Customer_Gender Product_Category       City  Order_Value  \
0       101            Male      Electronics       Pune         4500
1       102          Female         Clothing     Mumbai         2300
2       103          Female             Home      Delhi         3200
3       104            Male      Electronics  Bangalore         5200
4       105          Female           Beauty       Pune         1800
5       106            Male      Electronics  Hyderabad         4100

   Gender_Label  City_Label  Payment_Method_Credit Card  \
0             1           4                       False
1             0           3                        True
2             0           1                       False
3             1           0                       False
4             0           4                       False
5             1           2                       False

   Payment_Method_Debit Card  Payment_Method_UPI
0                      False                True
1                      False               False
2                       True               False
3                      False               False
4                      False                True
5                       True               False

# DIY Exercise
We are tasked to perform the operations learnt in the experiment on new datasets.
2 Datasets are given by the professor, we are performing the operations on it by writing the code.

In [26]:
# Amazon Product Dataset: Normalization
import pandas as pd

df = pd.read_csv("Amazon_dataset_Expt-15.csv")

# Apply Min-Max Normalization on Price column
df['Price'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())

# Display updated dataset
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold
0,P101,Wireless Mouse,0.020243,4.3,1520,350
1,P102,Bluetooth Speaker,0.048583,4.5,980,220
2,P103,USB Keyboard,0.016194,4.1,870,180
3,P104,Gaming Headset,0.089069,4.6,2100,410
4,P105,Smartwatch,0.149798,4.4,3050,520
5,P106,Power Bank,0.036437,4.2,1750,390
6,P107,Laptop Stand,0.024291,4.0,620,140
7,P108,Webcam,0.064777,4.3,1120,260
8,P109,Portable SSD,0.210526,4.7,1850,330
9,P110,Wireless Charger,0.028340,4.2,760,190
10,P111,Noise Cancelling Headphones,0.311741,4.6,4200,610
11,P112,Mechanical Keyboard,0.174089,4.5,2100,290
12,P113,Gaming Mouse,0.052632,4.4,1300,340
13,P114,Tablet Stand,0.016194,4.1,540,120
14,P115,USB Hub,0.024291,4.2,870,200
15,P116,External Hard Drive,0.251012,4.6,2300,310
16,P117,Smartphone Tripod,0.036437,4.3,760,210
17,P118,Laptop Backpack,0.068826,4.4,1600,420
18,P119,Bluetooth Earbuds,0.109312,4.5,3500,530
19,P120,LED Desk Lamp,0.040486,4.3,980,260
20,P121,Phone Holder,0.008097,4.0,420,150
21,P122,Wireless Keyboard,0.089069,4.4,1450,310
22,P123,Portable Monitor,0.352227,4.6,1250,170
23,P124,Smart Plug,0.020243,4.2,720,210
24,P125,WiFi Router,0.129555,4.5,2100,390
25,P126,Graphics Tablet,0.174089,4.4,980,160
26,P127,VR Headset,0.514170,4.7,3100,140
27,P128,Microphone,0.076923,4.3,1300,270
28,P129,Smart Light Bulb,0.016194,4.2,880,240
29,P130,Laptop Cooling Pad,0.048583,4.3,990,260
30,P131,Action Camera,0.392713,4.6,2100,200
31,P132,Smart Doorbell,0.230769,4.5,1750,180
32,P133,Streaming Stick,0.129555,4.4,2500,430
33,P134,Portable Projector,0.473684,4.6,1450,120
34,P135,Gaming Chair,0.635628,4.7,2100,90
35,P136,Desk Organizer,0.012146,4.1,450,160
36,P137,USB Flash Drive,0.020243,4.2,900,320
37,P138,Phone Screen Protector,0.000000,4.0,600,380
38,P139,Laptop Sleeve,0.028340,4.3,720,210
39,P140,Wireless Presenter,0.048583,4.4,520,130
40,P141,Tablet Keyboard Case,0.109312,4.5,850,150
41,P142,Smart Thermostat,0.433198,4.6,1200,110
42,P143,Security Camera,0.190283,4.4,2100,260
43,P144,Drone Camera,1.000000,4.7,1800,70
44,P145,Electric Kettle,0.068826,4.3,1400,310
45,P146,Air Fryer,0.311741,4.6,2200,200
46,P147,Robot Vacuum,0.757085,4.5,1650,120
47,P148,Smart Scale,0.089069,4.4,980,170
48,P149,Digital Photo Frame,0.129555,4.3,870,150
49,P150,Portable Fan,0.028340,4.2,760,240

In [27]:
# Amazon Product Dataset: Z Score Normalization
import pandas as pd

df = pd.read_csv("Amazon_dataset_Expt-15.csv")

# Calculate mean and standard deviation of Price
mean_price = df['Price'].mean()
std_price = df['Price'].std()

# Apply Z-score normalization
df['Price'] = (df['Price'] - mean_price) / std_price

# Display result
df

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold
0,P101,Wireless Mouse,-0.692019,4.3,1520,350
1,P102,Bluetooth Speaker,-0.557310,4.5,980,220
2,P103,USB Keyboard,-0.711263,4.1,870,180
3,P104,Gaming Headset,-0.364869,4.6,2100,410
4,P105,Smartwatch,-0.076207,4.4,3050,520
5,P106,Power Bank,-0.615043,4.2,1750,390
6,P107,Laptop Stand,-0.672775,4.0,620,140
7,P108,Webcam,-0.480334,4.3,1120,260
8,P109,Portable SSD,0.212455,4.7,1850,330
9,P110,Wireless Charger,-0.653531,4.2,760,190
10,P111,Noise Cancelling Headphones,0.693559,4.6,4200,610
11,P112,Mechanical Keyboard,0.039258,4.5,2100,290
12,P113,Gaming Mouse,-0.538066,4.4,1300,340
13,P114,Tablet Stand,-0.711263,4.1,540,120
14,P115,USB Hub,-0.672775,4.2,870,200
15,P116,External Hard Drive,0.404897,4.6,2300,310
16,P117,Smartphone Tripod,-0.615043,4.3,760,210
17,P118,Laptop Backpack,-0.461090,4.4,1600,420
18,P119,Bluetooth Earbuds,-0.268648,4.5,3500,530
19,P120,LED Desk Lamp,-0.595799,4.3,980,260
20,P121,Phone Holder,-0.749752,4.0,420,150
21,P122,Wireless Keyboard,-0.364869,4.4,1450,310
22,P123,Portable Monitor,0.886000,4.6,1250,170
23,P124,Smart Plug,-0.692019,4.2,720,210
24,P125,WiFi Router,-0.172428,4.5,2100,390
25,P126,Graphics Tablet,0.039258,4.4,980,160
26,P127,VR Headset,1.655766,4.7,3100,140
27,P128,Microphone,-0.422601,4.3,1300,270
28,P129,Smart Light Bulb,-0.711263,4.2,880,240
29,P130,Laptop Cooling Pad,-0.557310,4.3,990,260
30,P131,Action Camera,1.078442,4.6,2100,200
31,P132,Smart Doorbell,0.308676,4.5,1750,180
32,P133,Streaming Stick,-0.172428,4.4,2500,430
33,P134,Portable Projector,1.463325,4.6,1450,120
34,P135,Gaming Chair,2.233090,4.7,2100,90
35,P136,Desk Organizer,-0.730508,4.1,450,160
36,P137,USB Flash Drive,-0.692019,4.2,900,320
37,P138,Phone Screen Protector,-0.788240,4.0,600,380
38,P139,Laptop Sleeve,-0.653531,4.3,720,210
39,P140,Wireless Presenter,-0.557310,4.4,520,130
40,P141,Tablet Keyboard Case,-0.268648,4.5,850,150
41,P142,Smart Thermostat,1.270883,4.6,1200,110
42,P143,Security Camera,0.116235,4.4,2100,260
43,P144,Drone Camera,3.965063,4.7,1800,70
44,P145,Electric Kettle,-0.461090,4.3,1400,310
45,P146,Air Fryer,0.693559,4.6,2200,200
46,P147,Robot Vacuum,2.810415,4.5,1650,120
47,P148,Smart Scale,-0.364869,4.4,980,170
48,P149,Digital Photo Frame,-0.172428,4.3,870,150
49,P150,Portable Fan,-0.653531,4.2,760,240

In [29]:
# Amazon Product Dataset: Decimal Scaling
import pandas as pd
df = pd.read_csv("Amazon_dataset_Expt-15.csv")

df['Price_Decimal'] = df['Price'] / 100000

print("\n Decimal Scaled Dataset \n")
print(df[['Product_Name', 'Price', 'Price_Decimal']])

 Decimal Scaled Dataset

                   Product_Name  Price  Price_Decimal
0                Wireless Mouse    799        0.00799
1             Bluetooth Speaker   1499        0.01499
2                  USB Keyboard    699        0.00699
3                Gaming Headset   2499        0.02499
4                    Smartwatch   3999        0.03999
5                    Power Bank   1199        0.01199
6                  Laptop Stand    899        0.00899
7                        Webcam   1899        0.01899
8                  Portable SSD   5499        0.05499
9              Wireless Charger    999        0.00999
10  Noise Cancelling Headphones   7999        0.07999
11          Mechanical Keyboard   4599        0.04599
12                 Gaming Mouse   1599        0.01599
13                 Tablet Stand    699        0.00699
14                      USB Hub    899        0.00899
15          External Hard Drive   6499        0.06499
16            Smartphone Tripod   1199        0.01199
17              Laptop Backpack   1999        0.01999
18            Bluetooth Earbuds   2999        0.02999
19                LED Desk Lamp   1299        0.01299
20                 Phone Holder    499        0.00499
21            Wireless Keyboard   2499        0.02499
22             Portable Monitor   8999        0.08999
23                   Smart Plug    799        0.00799
24                  WiFi Router   3499        0.03499
25              Graphics Tablet   4599        0.04599
26                   VR Headset  12999        0.12999
27                   Microphone   2199        0.02199
28             Smart Light Bulb    699        0.00699
29           Laptop Cooling Pad   1499        0.01499
30                Action Camera   9999        0.09999
31               Smart Doorbell   5999        0.05999
32              Streaming Stick   3499        0.03499
33           Portable Projector  11999        0.11999
34                 Gaming Chair  15999        0.15999
35               Desk Organizer    599        0.00599
36              USB Flash Drive    799        0.00799
37       Phone Screen Protector    299        0.00299
38                Laptop Sleeve    999        0.00999
39           Wireless Presenter   1499        0.01499
40         Tablet Keyboard Case   2999        0.02999
41             Smart Thermostat  10999        0.10999
42              Security Camera   4999        0.04999
43                 Drone Camera  24999        0.24999
44              Electric Kettle   1999        0.01999
45                    Air Fryer   7999        0.07999
46                 Robot Vacuum  18999        0.18999
47                  Smart Scale   2499        0.02499
48          Digital Photo Frame   3499        0.03499
49                 Portable Fan    999        0.00999

In [30]:
# Student Dataset: Turning categorical values into quantitative variables
df = pd.read_csv("Student_Dataset_Exp15.csv")
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,Placed,450000
1,102,Male,IT,7.5,1,85,Not Placed,0
2,103,Female,ENTC,9.1,0,96,Placed,550000
3,104,Male,Mechanical,6.8,2,78,Not Placed,0
4,105,Female,Computer,8.7,0,88,Placed,480000
5,106,Male,Civil,7.2,3,72,Not Placed,0
6,107,Female,IT,8.9,0,91,Placed,500000
7,108,Male,Computer,6.5,1,80,Not Placed,0
8,109,Female,ENTC,7.8,0,84,Placed,420000
9,110,Male,Mechanical,7.0,2,76,Not Placed,0

In [35]:
# Student Dataset: Label Encoding for Placement Status
from sklearn.preprocessing import LabelEncoder
import pandas as pd

df = pd.read_csv("Student_Dataset_Exp15.csv")

le = LabelEncoder()
df['Placement_Status'] = le.fit_transform(df['Placement_Status'])

df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,1,450000
1,102,Male,IT,7.5,1,85,0,0
2,103,Female,ENTC,9.1,0,96,1,550000
3,104,Male,Mechanical,6.8,2,78,0,0
4,105,Female,Computer,8.7,0,88,1,480000
5,106,Male,Civil,7.2,3,72,0,0
6,107,Female,IT,8.9,0,91,1,500000
7,108,Male,Computer,6.5,1,80,0,0
8,109,Female,ENTC,7.8,0,84,1,420000
9,110,Male,Mechanical,7.0,2,76,0,0

In [34]:
# Student Dataset: One Hot Encoding for Department
import pandas as pd
df = pd.read_csv("Student_Dataset_Exp15.csv")

dept_encoded = pd.get_dummies(df['Department'], prefix='Dept')

df = pd.concat([df, dept_encoded], axis=1)

df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Dept_Civil,Dept_Computer,Dept_ENTC,Dept_IT,Dept_Mechanical
0,101,Female,Computer,8.2,0,92,Placed,450000,False,True,False,False,False
1,102,Male,IT,7.5,1,85,Not Placed,0,False,False,False,True,False
2,103,Female,ENTC,9.1,0,96,Placed,550000,False,False,True,False,False
3,104,Male,Mechanical,6.8,2,78,Not Placed,0,False,False,False,False,True
4,105,Female,Computer,8.7,0,88,Placed,480000,False,True,False,False,False
5,106,Male,Civil,7.2,3,72,Not Placed,0,True,False,False,False,False
6,107,Female,IT,8.9,0,91,Placed,500000,False,False,False,True,False
7,108,Male,Computer,6.5,1,80,Not Placed,0,False,True,False,False,False
8,109,Female,ENTC,7.8,0,84,Placed,420000,False,False,True,False,False
9,110,Male,Mechanical,7.0,2,76,Not Placed,0,False,False,False,False,True

In [33]:
# Student Dataset: Dummies for Department
import pandas as pd
df = pd.read_csv("Student_Dataset_Exp15.csv")

dept_dummies = pd.get_dummies(df['Department'], drop_first=True)

df = pd.concat([df, dept_dummies], axis=1)

df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Computer,ENTC,IT,Mechanical
0,101,Female,Computer,8.2,0,92,Placed,450000,True,False,False,False
1,102,Male,IT,7.5,1,85,Not Placed,0,False,False,True,False
2,103,Female,ENTC,9.1,0,96,Placed,550000,False,True,False,False
3,104,Male,Mechanical,6.8,2,78,Not Placed,0,False,False,False,True
4,105,Female,Computer,8.7,0,88,Placed,480000,True,False,False,False
5,106,Male,Civil,7.2,3,72,Not Placed,0,False,False,False,False
6,107,Female,IT,8.9,0,91,Placed,500000,False,False,True,False
7,108,Male,Computer,6.5,1,80,Not Placed,0,True,False,False,False
8,109,Female,ENTC,7.8,0,84,Placed,420000,False,True,False,False
9,110,Male,Mechanical,7.0,2,76,Not Placed,0,False,False,False,True